if(NOT DEFINED CUBIN_DIR)
  message(FATAL_ERROR "CUBIN_DIR not set")
endif()

if(NOT DEFINED CUBIN_PREFIX)
  message(FATAL_ERROR "CUBIN_PREFIX not set")
endif()

if(NOT DEFINED CUBIN_OUTPUT)
  message(FATAL_ERROR "CUBIN_OUTPUT not set")
endif()

# Try to find cubin files for any architecture (sm_86, sm_89, etc.)
# Prefer sm_89 if available, otherwise use the first one found
set(CUBIN_FILE_2_89 "${CUBIN_DIR}/${CUBIN_PREFIX}.2.sm_89.cubin")
set(CUBIN_FILE_1_89 "${CUBIN_DIR}/${CUBIN_PREFIX}.1.sm_89.cubin")
set(CUBIN_FILE_2_86 "${CUBIN_DIR}/${CUBIN_PREFIX}.2.sm_86.cubin")
set(CUBIN_FILE_1_86 "${CUBIN_DIR}/${CUBIN_PREFIX}.1.sm_86.cubin")

# Try sm_89 first, then sm_86, then any other architecture
if(EXISTS "${CUBIN_FILE_2_89}")
  if(EXISTS "${CUBIN_OUTPUT}")
    file(REMOVE "${CUBIN_OUTPUT}")
  endif()
  file(RENAME "${CUBIN_FILE_2_89}" "${CUBIN_OUTPUT}")
  if(EXISTS "${CUBIN_FILE_1_89}")
    file(REMOVE "${CUBIN_FILE_1_89}")
  endif()
elseif(EXISTS "${CUBIN_FILE_1_89}")
  if(EXISTS "${CUBIN_OUTPUT}")
    file(REMOVE "${CUBIN_OUTPUT}")
  endif()
  file(RENAME "${CUBIN_FILE_1_89}" "${CUBIN_OUTPUT}")
elseif(EXISTS "${CUBIN_FILE_2_86}")
  if(EXISTS "${CUBIN_OUTPUT}")
    file(REMOVE "${CUBIN_OUTPUT}")
  endif()
  file(RENAME "${CUBIN_FILE_2_86}" "${CUBIN_OUTPUT}")
  if(EXISTS "${CUBIN_FILE_1_86}")
    file(REMOVE "${CUBIN_FILE_1_86}")
  endif()
elseif(EXISTS "${CUBIN_FILE_1_86}")
  if(EXISTS "${CUBIN_OUTPUT}")
    file(REMOVE "${CUBIN_OUTPUT}")
  endif()
  file(RENAME "${CUBIN_FILE_1_86}" "${CUBIN_OUTPUT}")
else()
  # Try to find any cubin file with the prefix
  file(GLOB CUBIN_FILES "${CUBIN_DIR}/${CUBIN_PREFIX}.*.cubin")
  if(CUBIN_FILES)
    list(GET CUBIN_FILES 0 FIRST_CUBIN)
    if(EXISTS "${CUBIN_OUTPUT}")
      file(REMOVE "${CUBIN_OUTPUT}")
    endif()
    file(RENAME "${FIRST_CUBIN}" "${CUBIN_OUTPUT}")
  else()
    message(WARNING "cuobjdump did not produce ${CUBIN_PREFIX}.*.sm_89.cubin or ${CUBIN_PREFIX}.*.sm_86.cubin. Continuing anyway.")
  endif()
endif()
