if(NOT DEFINED CUBIN_DIR)
  message(FATAL_ERROR "CUBIN_DIR not set")
endif()

if(NOT DEFINED CUBIN_PREFIX)
  message(FATAL_ERROR "CUBIN_PREFIX not set")
endif()

if(NOT DEFINED CUBIN_OUTPUT)
  message(FATAL_ERROR "CUBIN_OUTPUT not set")
endif()

set(CUBIN_FILE_2 "${CUBIN_DIR}/${CUBIN_PREFIX}.2.sm_89.cubin")
set(CUBIN_FILE_1 "${CUBIN_DIR}/${CUBIN_PREFIX}.1.sm_89.cubin")

if(EXISTS "${CUBIN_FILE_2}")
  if(EXISTS "${CUBIN_OUTPUT}")
    file(REMOVE "${CUBIN_OUTPUT}")
  endif()
  file(RENAME "${CUBIN_FILE_2}" "${CUBIN_OUTPUT}")
  if(EXISTS "${CUBIN_FILE_1}")
    file(REMOVE "${CUBIN_FILE_1}")
  endif()
elseif(EXISTS "${CUBIN_FILE_1}")
  if(EXISTS "${CUBIN_OUTPUT}")
    file(REMOVE "${CUBIN_OUTPUT}")
  endif()
  file(RENAME "${CUBIN_FILE_1}" "${CUBIN_OUTPUT}")
else()
  message(FATAL_ERROR "cuobjdump did not produce ${CUBIN_PREFIX}.*.sm_89.cubin")
endif()
